- name: Cisco setup ospf
  hosts: R1:R2
  gather_facts: false

  tasks:
    - name: configure ospf
      ios_config:
        lines:
          - router ospf 1
          - network 192.128.4.0 0.0.0.255 area 0
      register: output

    - name: print output
      debug:
        var: output.stdout_lines