- name: Cisco show ip route
  hosts: R1:R2
  gather_facts: false


  tasks:
    - name: display ip route table
      ansible.netcommon.ios.ios_command:
        commands:
          - show ip route
      register: route_table_output

    - name: print route table output
      debug:
        msg: "{{ route_table_output.stdout_lines }}"